<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It is a breeze. Simply tell Lumen the URIs it should respond to
| and give it the Closure to call when that URI is requested.
|
*/


/**
 * Swagger Todo BoardController
 * This is a sample server Post server
 *
 * OpenAPI spec version: 1.0.0-beta
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Swagger Todo BoardController
 * @version 1.0.0-beta
 */

$router->get('/', function(){
    return response()->json(["message" => "Made with 💛 using cheese."]);
});

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/home', 'HomeController@index');


$router->group(['prefix' => 'boards'], function () use ($router) {

  /**
   * post store
   * Summary: Add a new board
   * Notes: Create new todo cards
   * Output-Formats: [application/json]
   */
  $router->post('', 'BoardController@store');

  /**
 * get index
 * Summary: This show all the cards
 * Notes:
 * Output-Formats: [application/json]
 */
$router->get('/{board}', 'BoardController@index');

  /**
   * get show
   * Summary: Show a specific board based on the board Id
   * Notes:
   * Output-Formats: [application/json]
   */
  $router->get('/{board}', 'BoardController@show');

/**
 * delete delete
 * Summary: Delete a card
 * Notes:
 * Output-Formats: [application/json]
 */
$router->delete('/{board}', 'BoardController@delete');
/**
 * post update
 * Summary: Update an existing card
 * Notes: Card object that needs to be updated to the store
 * Output-Formats: [application/json]
 */
$router->put('/{board}', 'BoardController@update');
});

$router->group(['prefix' => 'user'], function () use ($router) {

/**
 * post registerUser
 * Summary: Create user
 * Notes: This can only be done by the logged in user.
 * Output-Formats: [application/json]
 */
$router->post('/registration', 'AuthController@register');

/**
 * get loginUser
 * Summary: Logs user into the system
 * Notes:
 * Output-Formats: [application/json]
 */
$router->get('login', 'AuthController@loginUser');

/**
 * get logoutUser
 * Summary: Logs out current logged in user session
 * Notes:
 * Output-Formats: [application/json]
 */
$router->get('logout', 'AuthController@logoutUser');


});
