<?php

/**
 * Swagger  BoardController
 * This is a sample server Post server
 *
 * OpenAPI spec version: 1.0.0-beta
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use App\Board;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
class BoardController extends Controller
{
  /**
   * Constructor
   */
  public function __construct()
  {
    $this->middleware('auth', ['only' => 'store']);
  }

  /**
   * Operation index
   *
   * This show all the cards.
   *
   *
   * @return Board[]|Http|\Illuminate\Database\Eloquent\Collection
   */
  public function index()
  {
    return Board::all();
  }

  public function show($board) {
    return Board::findOrFail($board);
  }

  /**
   * Operation store
   *
   * Add a new board.
   *
   *
   * @return JsonResponse response
   * @throws ValidationException
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'name' => 'required| max: 50',
      'user_id' => 'required|exists:users,id',
    ]);

    $board = Board::create($request->all());
    return response()->json(['board' => $board, 'message' => "{$board->name} board has been created"], '201');
  }

  /**
   * Operation delete
   *
   * Delete a card.
   *
   * @param int $board id to delete (required)
   *
   * @return JsonResponse response
   */
  public function delete($board) {

    if (Board::destroy($board)) {
      return response()->json(['board' => $board, 'message' => "board has been deleted"], '200');
    }
    return response()->json(['board' => $board, 'message' => "Something went wrong"], '200');
  }

  /**
   * Operation update
   *
   * Update an existing card.
   *
   * @param Request $request
   * @param $board
   * @return JsonResponse response
   * @throws ValidationException
   */
  public function update(Request $request, $board) {
    $this->validate($request, [
      'name' => 'required| max: 50',
    ]);
    $boardUpdate = Board::find($board);
    $boardUpdate->update($request->all());
    return response()->json(['update' => $boardUpdate, 'message' => "Board with Id of {$board} updated"], 200);
  }
}
